import { Metadata } from 'next'

export const siteConfig = {
  name: 'Disconnect Madison',
  description:
    'On a mission to help the people of Madison, WI free themselves from the grip of corporate tech and social media',
  url: 'https://disconnectmadison.org',
  // ogImage: 'https://thesiteofzeke.dev/opengraph-image', // Auto-generated by Next.js
  links: {
    linkedin: 'https://www.linkedin.com/in/davidewitter',
    email: 'mailto:disconnectmadison@proton.me',
  },
}

export const baseMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: [
    'Community',
    'Connection',
    'Local',
    'Freedom',
    'Wellness',
  ],
  authors: [{ name: siteConfig.name }],
  creator: siteConfig.name,
//   openGraph: {
//     type: 'website',
//     locale: 'en_US',
//     url: siteConfig.url,
//     title: siteConfig.name,
//     description: siteConfig.description,
//     siteName: siteConfig.name,
//     images: [
//       {
//         url: siteConfig.ogImage,
//         width: 1200,
//         height: 630,
//         alt: siteConfig.name,
//       },
//     ],
//   },
//   twitter: {
//     card: 'summary_large_image',
//     // No creator handle needed - Twitter will use OpenGraph data
//   },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}
