import { Metadata } from 'next'

export const siteConfig = {
  name: 'Disconnect Madison',
  description:
    'A community project in Madison, WI helping people step back from algorithm-driven social media',
  url: 'https://disconnectmadison.org',
  links: {
    linkedin: 'https://www.linkedin.com/in/davidewitter',
    email: 'mailto:hello@disconnectmadison.org',
  },
}

export const baseMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: [
    'Community',
    'Connection',
    'Local',
    'Freedom',
    'Wellness',
  ],
  authors: [{ name: siteConfig.name }],
  creator: siteConfig.name,
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
    // og:image is generated by app/opengraph-image.tsx (also reused for Twitter).
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.name,
    description: siteConfig.description,
  },
  alternates: {
    canonical: siteConfig.url,
  },
  // Favicons handled by file conventions: app/icon.svg + app/apple-icon.png
  // (modern), plus public/favicon.ico (legacy default request).
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}
